/** @format */

import { ThemeProvider } from '@/components/Theme';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: { default: 'Serguius.ru', template: '%s | Serguius.ru' },
	description: 'Generated by create next app',
};

export default function RootLayout(props: { children: React.ReactNode; modal: React.ReactNode }) {
	return (
		<html>
			<body>
				<ThemeProvider>
					{props.children}
					{props.modal}
				</ThemeProvider>
			</body>
		</html>
	);
}
